#!/usr/bin/env python3
"""Bundle the design system into dist/ (one CSS + one JS + fonts + assets).

Run from the repo root:  python3 build-dist.py
Regenerate whenever a component's CSS/JS changes. Do not hand-edit dist/.
"""
import glob, os, re, shutil

def strip_imports(css):
    return re.sub(r'^\s*@import[^;]*;\s*$', '', css, flags=re.M)

os.makedirs('dist', exist_ok=True)

# ---- CSS: tokens, typography, then every component (A–Z) ----
parts = ["/* Zego Design System — bundled stylesheet (generated by build-dist.py). Do not edit. */\n"]
tokens = open('tokens/tokens.css').read().replace("url('../fonts/", "url('fonts/")
parts.append("/* ==== tokens/tokens.css ==== */\n" + tokens)
parts.append("\n/* ==== tokens/typography.css ==== */\n" + strip_imports(open('tokens/typography.css').read()))
for f in sorted(glob.glob('components/*/*.css')):
    css = strip_imports(open(f).read()).replace("url('../../assets/partners/", "url('assets/partners/")
    parts.append("\n/* ==== %s ==== */\n" % f + css)
open('dist/zego-ds.css', 'w').write('\n'.join(parts))

# ---- JS: every component behaviour concatenated (self-init IIFEs) ----
js = ["/* Zego Design System — bundled behaviour (generated by build-dist.py). */\n"]
for f in sorted(glob.glob('components/*/*.js')):
    js.append("\n/* ==== %s ==== */\n" % f + open(f).read())
open('dist/zego-ds.js', 'w').write('\n'.join(js))

# ---- copy fonts + assets ----
for d in ('fonts', 'assets'):
    dst = os.path.join('dist', d)
    if os.path.exists(dst):
        shutil.rmtree(dst)
    shutil.copytree(d, dst, ignore=shutil.ignore_patterns('.DS_Store', 'README.md'))

# ---- ready-to-copy HTML snippets (one per component, scaffolding stripped) ----
def _title(name): return name.replace('-', ' ').title()

os.makedirs('dist/components', exist_ok=True)
for f in glob.glob('dist/components/*.html'):
    os.remove(f)
for demo in sorted(glob.glob('components/*/*-demo.html')):
    name = os.path.basename(demo)[:-len('-demo.html')]
    b = open(demo).read()
    m = re.search(r'<body[^>]*>(.*)</body>', b, re.S | re.I)
    b = m.group(1) if m else b
    b = re.sub(r'<script\b.*?</script>', '', b, flags=re.S | re.I)
    b = re.sub(r'<style\b.*?</style>', '', b, flags=re.S | re.I)
    b = re.sub(r'<span class="label">.*?</span>', '', b, flags=re.S)
    b = re.sub(r'<h1\b[^>]*>.*?</h1>', '', b, flags=re.S | re.I)
    b = re.sub(r'<h2\b[^>]*>.*?</h2>', '', b, flags=re.S | re.I)
    b = re.sub(r'<p class="subtitle">.*?</p>', '', b, flags=re.S | re.I)
    b = re.sub(r'\sdata-theme=(["\'])dark\1', '', b)
    if re.search(r'<section\s+class=', b) is None:            # unwrap demo-only <section> groups
        b = re.sub(r'</?section[^>]*>', '', b, flags=re.I)
    lines = b.split('\n')
    indents = [len(l) - len(l.lstrip()) for l in lines if l.strip()]
    cut = min(indents) if indents else 0
    b = '\n'.join(l[cut:] if len(l) >= cut else l for l in lines)
    b = re.sub(r'\n[ \t]*\n[ \t]*\n+', '\n\n', b).strip()
    header = ("<!-- %s — Zego Design System\n"
              "     Paste into a page that loads dist/zego-ds.css + dist/zego-ds.js. -->\n\n" % _title(name))
    open('dist/components/%s.html' % name, 'w').write(header + b + '\n')

print("Built dist/zego-ds.css (%d bytes), dist/zego-ds.js (%d bytes), %d component snippets"
      % (os.path.getsize('dist/zego-ds.css'), os.path.getsize('dist/zego-ds.js'),
         len(glob.glob('dist/components/*.html'))))
